site_name: MHIM Intern Resource
site_url: https://www.mhim-handbook.com

nav:
  - Home: index.md
  - Housing: Housing.md
  - SSN Acquisition: SSN Acquisition.md 
  - Child Care: Child Care.md 
  - Transportation: Transportation.md 
  - Banking Resources: Banking Resources.md 


theme: 
  name: material
  logo: images/favicon.png 
  favicon: images/favicon.png 

  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode




extra: 
  homepage: https://ofolimensah.github.io/Intern_Starter_Pack/

