site_name: MHIM Intern Resource
site_url: https://ofolimensah.github.io/Intern_Starter_Pack/

nav:
  - Home: index.md
  - Housing: Housing.md
  - SSN Acquisition: SSN Acquisition.md 
  - Child Care: Child Care.md 
  - Transportation: Transportation.md 
  - Banking Resources: Banking Resources.md 
  - Welcome Message from Chief Residents: Welcome Message from Chief Residents.md

theme: 
  name: material
  logo: images/favicon.png 
  favicon: images/favicon.png 



extra: 
  homepage: https://ofolimensah.github.io/Intern_Starter_Pack/

