site_name: MHIM Intern Resource
site_url: https://ofolimensah.github.io/Intern_Starter_Pack/
nav:
  - Home: index.md
  - Housing: Housing.md
  - SSN Acquisition: SSN Acquisition.md 
  - Child Care: Child Care.md 
  - Transportation: Transportation.md 
  - Banking Resources: Banking Resources.md 


theme: 
  name: material
  icon:
    logo: images/favicon.png 
  favicon: images/favicon.png 
  features:
    - navigation.sections


extra: 
  homepage: https://ofolimensah.github.io/Intern_Starter_Pack/

